[IOSPAY-716] add Any decoding
yandex-money/core-api-swift pull request #22
Opened 2019-10-01 15:54 UTC by emazalova

2019-10-01 16:57 UTC, subtranix submitted a review, later dismissed

2019-10-02 07:14 UTC, MetalheadSanya requested changes
Please, append some tests for new decode methos

2019-10-03 11:44 UTC, emazalova commented
> Please, append some tests for new decode methos

fxd

2019-10-03 11:50 UTC, MetalheadSanya submitted a review, later dismissed

2019-10-03 13:25 UTC, subtranix submitted a review, later dismissed

2019-10-03 13:26 UTC, MetalheadSanya submitted a review, later dismissed

2019-10-07 08:59 UTC, subtranix approved these changes

2019-10-07 09:03 UTC, merged